### ISSUE TITLE
Infotext: Anonyme Teilnahme

### ISSUE THREAD

**Issue by vermayer** [uol-studip/stoodle#23]
in edit.php in Zeile 189 bitte 
"Die Namen der Teilnehmenden sind für andere Teilnehmende nicht sichtbar." ändern in:
 
"Die Namen der Teilnehmenden sind für andere Teilnehmende, Mitwirkende und Dozierende nicht sichtbar."

**Comment by tleilax** [comment]
Fixed in 0d792aa9224b451715a7fac374b1369e6ed85831
