### ISSUE TITLE
Anonyme Kommentare

### ISSUE THREAD

**Issue by vermayer** [uol-studip/stoodle#24]
Wäre es möglich, bei einer anonymen Umfrage auch die Kommentare zu anonymisieren?
Aktuell werden auch bei einer anonymen Umfrage die Namen unterhalb der Kommentare angezeigt.

**Comment by tleilax** [comment]
Ja, das ist möglich. Werde ich in die nächste Version einbauen.

**Comment by tleilax** [comment]
Ist in Version 2.3.7 gefixt.
